### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by kevva** [kevva/caw#1]
Couldn't get the tests to work so I'm not 100% this works. @floatdrop, you'd probably know how to fix this I guess :).

**Comment by floatdrop** [comment]
@kevva dunno, could you push test in branch? - I can take a look.

**Comment by floatdrop** [comment]
Added basic test, seems working to me.

**Comment by floatdrop** [comment]
@kevva can you publish it? I want to use it in [proxy-support](https://github.com/floatdrop/proxy-support).

**Comment by kevva** [comment]
@floatdrop, done!

**Comment by floatdrop** [comment]
@kevva thanks! :tada:
