### ISSUE TITLE
Can you please publish the 2.0.1 to npm ?

### ISSUE THREAD

**Issue by Ilshidur** [kevva/caw#20]
The 2.0.0 version also contains a [vulnerability](https://snyk.io/test/npm/caw/2.0.0) introduced through the `tunnel-agent@0.4.3` package, which you updated to the `0.6.0` version in `caw@2.0.1`, but didn't published.

It would be nice if the GitHub package was the same as the one in the npm registry.

**Comment by kevva** [comment]
Should be published now.
